### ISSUE TITLE
Docker volumes in docker compose not working

### ISSUE THREAD

**Issue by dct0** [codersforcauses/automated-setups#10]
## Basic Information
I want to be able to specify docker volumes in a docker compose and run `docker compose up` in a dev container to start everything up. The bind mounts don't seem to work in this case, and it's likely something to do with the docker-in-docker situation.

## Other Information
https://github.com/h4l/dev-container-docker-compose-volume-or-bind

**Comment by dct0** [comment]
Or maybe the `LOCAL_WORKSPACE_FOLDER` env...

**Comment by frinzekt** [comment]
do you have steps of replication?

when you run docker compose, it uses the path of the host, isn't it? That other notes seems interesting though

**Comment by frinzekt** [comment]
yeah you maybe are right with the local workspace folder env set in https://github.com/codersforcauses/automated-setups/blob/main/cfc-devenv-base/.devcontainer/devcontainer.json

**Comment by dct0** [comment]
There ended up being (not really) a bug with docker desktop for mac which made it so the bind mounts didn't work https://github.com/microsoft/vscode-remote-release/issues/5388#issuecomment-1259437096 in the docker compose. The solution was to use the `LOCAL_WORKSPACE_FOLDER` env var so I'm thinking it can also be applied to other containers so the bind mounts work properly https://github.com/codersforcauses/django-nextjs-template/blob/main/docker-compose.yml#L6 . Then we can dockerise the entire app which makes running stuff much easier

**Comment by frinzekt** [comment]
Are you proposing to use django app dockerised and running in another container?

I'm not opposed to it, but there's a couple of advantages to running django in the devcontainer rather than in another container. Some of the advantages i see are:
- debugger is directly integrated to the IDE (yes, I would like CFC volunteers to learn how to use debugger of the IDE)
- the terminal you use to do migrate, and run scripts is the devcontainer with the shell setup

**Comment by dct0** [comment]
Can confirm I was able to dockerise entire apps with the env var, so I'm closing this issue
