### ISSUE TITLE
Intellisense for Python package installed from poetry

### ISSUE THREAD

**Issue by frinzekt** [codersforcauses/automated-setups#7]
## Basic Information
As a developer, when i have poetry dependencies installed, I want my intellisense of my vscode to work in the devcontainers.

## Other Information
If you create `~/.zshenv`, you can set variables there. There's currently a bug where i set variables in `~/.zshrc` that won't work. Even then, im not sure setting the env variable is the right fix.

When you did `pip3 install sqlparse` for example, that will be recognised by the IDE. It feels like this is a poetry specific problem :( . Maybe worth considering to use pipenv or something else with a lockfile that will make this possible.

**Comment by dct0** [comment]
I ended up creating a `.zshrc` that gets appended in the dockerfile which seems to do the job. The poetry env flag makes it install the the deps outside instead of inside a venv which allows vscode to recognise it. Otherwise I think you have to tell poetry to create the venv in the project and make sure it's activated when the container starts
https://github.com/codersforcauses/automated-setups/commit/b869c43409e5f2bb7b71a4f03adca16b6e34656a
